# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: is_msgs/ros.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'is_msgs/ros.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from is_msgs import common_pb2 as is__msgs_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11is_msgs/ros.proto\x12\x06is.ros\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14is_msgs/common.proto\"D\n\nROSMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12(\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"<\n\tTFMessage\x12/\n\ntransforms\x18\x01 \x03(\x0b\x32\x1b.is.common.TransformStampedB\x0e\n\ncom.is.rosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'is_msgs.ros_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.is.rosP\001'
  _globals['_ROSMESSAGE']._serialized_start=81
  _globals['_ROSMESSAGE']._serialized_end=149
  _globals['_TFMESSAGE']._serialized_start=151
  _globals['_TFMESSAGE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
